name: UnlockEgypt
options:
  bundleIdPrefix: com.unlockegypt
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  UnlockEgypt:
    type: application
    platform: iOS
    sources:
      - path: Sources
        type: group
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        PRODUCT_BUNDLE_IDENTIFIER: com.unlockegypt.app
        PRODUCT_NAME: "Unlock Egypt"
        GENERATE_INFOPLIST_FILE: NO
    resources:
      - path: Resources/Assets.xcassets
      - path: Resources/unlock_egypt_content.json
      - path: Resources/Images
        optional: true
      - path: Resources/Audio
        optional: true
